### ISSUE TITLE
Access control

### ISSUE THREAD

**Issue by agentphoenix** [anodyne/nova3#36]
**Task Management**
- [x] Add task
- [x] Edit task
- [x] Delete task

**Role Management**
- [x] Add role
- [x] Edit role
- [x] Duplicate role
- [x] Delete role (making sure to change anyone who has that role currently)
- [x] User session updates when a role is changed
- [x] Add inherited roles (and their tasks)
- [x] Remove inherited roles (and their tasks)

**Docs**
- [x] What is a task? What is an action? What is a component?
- [x] What is a role?
- [x] What is role inheritance?
- [x] 3rd-party devs: How do I tap into access control for my own stuff?
- [x] 3rd-party devs: What is Sentry? How do I use it?
