### ISSUE TITLE
alpha.1

### ISSUE THREAD

**Issue by agentphoenix** [anodyne/nova3#92]
#### Overview

To kick off the process of Nova NextGen, it's important to get the technology stack figured out and the application architecture started, including a basic theme setup and many of the different pieces that Nova will need as the rest of the application is developed.

#### Tasks

- [x] Use form request class to validate user/character creation
- [x] PostgreSQL database driver option
- [x] Test sqlite support

**Comment by agentphoenix** [comment]
Closed by 0e59b04
